# Generated by Django 4.0.3 on 2022-04-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img4', models.ImageField(upload_to='pics')),
                ('heading', models.CharField(max_length=100)),
                ('img5', models.ImageField(upload_to='pics')),
                ('heading2', models.CharField(max_length=100)),
                ('paragraph', models.CharField(max_length=100)),
            ],
        ),
    ]
