# Generated by Django 4.0.3 on 2022-05-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_portfoliodetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioDetails',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='prim_img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.AddField(
            model_name='post',
            name='heading',
            field=models.CharField(default='kjj', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='heading2',
            field=models.CharField(default='klk', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph',
            field=models.CharField(default='kjlk', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='sec_img',
            field=models.ImageField(default='kjkj', upload_to='pics'),
            preserve_default=False,
        ),
    ]
