# Generated by Django 4.0.3 on 2022-05-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_post_details_delete_aboutproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_details',
            name='posted_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post_details',
            name='primary_heading',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='post_details',
            name='primary_paragraph',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='heading2',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
