# Generated by Django 4.0.3 on 2022-05-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_post_details_primary_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_details',
            old_name='fashionContent',
            new_name='BlogContent',
        ),
        migrations.RenameField(
            model_name='post_details',
            old_name='fashiondes',
            new_name='Blogdes',
        ),
        migrations.RenameField(
            model_name='post_details',
            old_name='fashiontitle',
            new_name='Blogtitle',
        ),
    ]
