# Generated by Django 4.0.3 on 2022-05-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_blogcomment_parent_subcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='portfolios',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='parentComment',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
        migrations.DeleteModel(
            name='SubComment',
        ),
    ]
