# Generated by Django 4.0.3 on 2022-05-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_blogcomment_parent_remove_blogcomment_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
