# Generated by Django 4.0.3 on 2022-06-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sec_head',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
