# Generated by Django 4.0.5 on 2022-07-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_post_details_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_details',
            name='Blogdes',
        ),
    ]
